language: ruby
rvm:
  - 2.4.2

sudo: false

cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - USER="Travis CI"
    - EMAIL="travis@travis-ci.org"
    - GITHUB_REPO="github.com/${TRAVIS_REPO_SLUG}.git"

branches:
  only:
    - master
    - develop

before_install:
  - gem install gem-release --pre
  - ./scripts/bump-version.sh

script:
  - bundle exec jekyll build --config _test/_config.yml
  - bundle exec htmlproofer ./_site --disable-external

after_success:
  - ./scripts/merge-downstream.sh

deploy:
  - provider: rubygems
    on:
      branch: master
    api_key: ${RUBYGEMS_TOKEN}
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: "resume-theme-$(gem bump --pretend --no-commit | awk '{ print $3 }').gem"
    on:
      branch: master
