# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Abhijeet Gulve
title: Software Engineer
email: abhigulve06@gmail.com
website: https://abhigulve.github.io/modern-resume-theme/

# Social links
twitter_username: abhijeetgulve
github_username:  abhigulve
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: abhijeet_gulve
linkedin_username: abhijeet-gulve
# pinterest_username: jekyll
youtube_username: NA
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, I'm Abhijeet and I'm a Software developer.Having good knowledge and hands-on experience of data structures, algorithms, and object -
oriented programming.Having Around 5 years of hands on experience in Development and Deployment of web
based applications using Java and Python.Having strong experience in working with Geospatial systems
  I am most skilled in: <mark>Java</mark> , <mark>Python</mark> <mark>Data structure</mark>  and <mark>Algorithms</mark>
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in  software engineering some of my other interests and hobbies are:
   - Tracking
   - Swiming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
