# Site
repository: https://github.com/S1erra-Xray/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sierra
title: System administrator and Software developer
email: Email is hidden
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://S1erra-Xray.github.io/modern-resume-theme/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: S1erra-Xray
telegram_username: sierra_xray


# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm known online as Sierra. IT sphere
  I have been training since 2019 and during this time I have managed to learn a lot and also try. 
  In addition to administration, my skills include developing applications and automating my routine tasks. 
  
  I have a high <mark>typing speed</mark> and can <mark>argue</mark> well :)
content:
  - title: Projects # Title for the section
    layout: text # Type of content section (list/text)
    content:
      New projects will be described here soon
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Coming soon
        sub_title: Linux administration
        caption: November 2023 - today
        link: example.com
        quote: >

        description: | # this will include new lines to allow paragraphs
          Junior linux system administrator
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: College name
        sub_title: Yevhen Paton Applied College
        caption: 2023 - today
        quote: >
          Ð¡ourse for training junior system administrators
        description: | # this will include new lines to allow paragraphs
          Administration of operating systems and servers in general
  - title: A Little More About Me
    layout: text
    content: # this will include new lines to allow paragraphs
      I love linux and use it on a regular basis. Of the non-human languages, I like Python and C#.
      <br>
      Also like reading technical literature in terms of books and other articles more than watching videos on youtube.
      <br>
      I like to peel back layers of abstraction and learn things at a deep level.
      <br>
      ![Typing SVG](https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&color=000000FF&random=false&width=435&lines=That's+all+for+now!)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: S1erra-Xray/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
